import {CONFIG} from '../config/gameConfig.js';import {Logger} from '../core/Logger.js';import {EventDeduplicator} from '../core/EventDeduplicator.js';import {validateEvent} from '../events/EventValidator.js';import {createHabitant} from '../entities/Habitant.js';import {newSeason} from '../systems/Season.js';import {GlobalEventMachine} from '../systems/GlobalEvents.js';
export class Game {
 constructor({config=CONFIG,storage=null,audio=null}={}){this.config=config;this.storage=storage;this.audio=audio;this.log=new Logger();this.listeners=[];this.reset();const saved=storage?.load();if(saved)this.restore(saved)}
 reset(){this.season=newSeason(this.config);this.habitants=[];this.discoveries={moonTemple:false,meteorShard:false,eclipseGate:false};this.feed=[];this.stats={processed:0,ignored:0,failed:0,likes:0};this.dedup=new EventDeduplicator([] ,this.config.maxEventIds);this.events=new GlobalEventMachine(this.config);this.lastLikeFlush=Date.now()}
 restore(s){try{this.season=s.season;this.habitants=Array.isArray(s.habitants)?s.habitants:[];this.discoveries=s.discoveries||{};this.feed=s.feed||[];this.stats=s.stats||this.stats;this.dedup=new EventDeduplicator(s.eventIds||[],this.config.maxEventIds);this.events=new GlobalEventMachine(this.config);if(s.currentEvent)this.events.current=s.currentEvent}catch(e){this.log.add('error','Estado salvo inválido');this.reset()}}
 snapshot(){return {season:this.season,habitants:this.habitants,discoveries:this.discoveries,feed:this.feed.slice(0,25),stats:this.stats,eventIds:this.dedup.values(),currentEvent:this.events.current}}
 save(){return this.storage?.save(this.snapshot())}
 onChange(fn){this.listeners.push(fn);return()=>this.listeners=this.listeners.filter(x=>x!==fn)}notify(){this.listeners.forEach(f=>f(this));}
 addFeed(message){this.feed.unshift({message,time:Date.now()});this.feed.length=25}
 person(e,create=true){let p=this.habitants.find(x=>x.id===e.userId);if(!p&&create){p=createHabitant(e.userId,e.username);this.habitants.push(p);this.addFeed(`${p.name} chegou à ilha!`)}return p}
 score(p,field,value){if(!p||!Number.isFinite(value)||value<=0)return; p[field]=Math.min(this.config.maxScore,(p[field]||0)+value);p.experience=Math.min(this.config.maxScore,p.experience+value);p.level=Math.max(1,Math.floor(p.experience/100)+1);for(const t of this.config.titles)if((p[t.field]||0)>=t.min){p.title=t.name;break}}
 progress(value,reason){const rainBoost=this.events.current?.type==='rain'?1.5:1;const v=Math.max(0,Math.min(this.config.maxScore,Math.round(value*rainBoost)));this.season.progress=Math.min(this.config.maxScore,this.season.progress+v);let era=this.season.era;while(era<this.config.eras.length&&this.season.progress>=this.config.eras[era].threshold)era++;if(era!==this.season.era){this.season.era=era;this.addFeed(`✨ Era ${era}: ${this.config.eras[era-1].name}!`);this.audio?.play('discovery')}if(reason)this.addFeed(reason)}
 process(raw){try{const e=validateEvent(raw,this.config);if(!e){this.stats.ignored++;return false}if(this.dedup.seen(e.id)){this.stats.ignored++;return false}this.stats.processed++;const p=this.person(e,e.type!=='like');if(e.type==='gift')this.gift(e,p);else if(e.type==='like'){this.stats.likes+=e.likeCount;this.flushLikes(false)}else if(e.type==='follow'){this.score(p,'contribution',12);this.progress(12,`${p.name} seguiu a comunidade.`);this.audio?.play('reward')}else if(e.type==='join')this.addFeed(`${e.username} está assistindo.`);else if(e.type==='comment')this.command(e,p);else if(e.type==='share')this.addFeed(`${e.username} compartilhou a LIVE.`);this.save();this.notify();return true}catch(err){this.stats.failed++;this.log.add('error',String(err));return false}}
 gift(e,p){if(e.diamondCount===null){this.addFeed(`${e.username} enviou um presente sem valor informado.`);return}if(!e.repeatEnd)return;const tier=this.config.giftTiers.find(t=>e.diamondCount>=t.min&&e.diamondCount<=t.max);if(!tier)return;const amount=tier.points*e.repeatCount;this.score(p,'contribution',amount);this.progress(amount,`${p.name} ajudou a construir a cidade (+${amount}).`);this.events.contribute(amount);if(tier.special){this.startEvent('meteor');this.discoveries.meteorShard=true}this.audio?.play(tier.effect?'reward':'build')}
 flushLikes(force=true){if(!force&&Date.now()-this.lastLikeFlush<this.config.likeAggregationMs)return 0;const units=Math.floor(this.stats.likes/this.config.likesPerEnergy);if(units){this.stats.likes-=units*this.config.likesPerEnergy;this.progress(units,`${units} energia comunitária foi gerada.`)}this.lastLikeFlush=Date.now();return units}
 command(e,p){const c=e.comment.trim().toLowerCase();const map={'!explorar':['exploration',10,'explorou novas terras.'],'!construir':['contribution',10,'ajudou a construir a praça.'],'!defender':['defense',10,'reforçou as defesas.']};const x=map[c];if(!x)return;this.score(p,x[0],x[1]);if(x[0]==='contribution')this.progress(x[1]);if(x[0]==='defense')this.events.contribute(x[1]);this.addFeed(`${p.name} ${x[2]}`);this.audio?.play('build')}
 startEvent(type){if(this.events.start(type)){this.addFeed(`🌟 Evento global: ${type.toUpperCase()}`);if(type==='rain')this.addFeed('A chuva acelera o crescimento em 50%.');if(type==='meteor')this.addFeed('Um meteoro pode revelar uma descoberta.');if(type==='eclipse')this.addFeed('O eclipse pode abrir uma área misteriosa.');this.audio?.play('event');this.notify();return true}return false}
 tick(){this.flushLikes(false);const end=this.events.tick();if(end){if(end.won){if(end.event.type==='meteor')this.unlock('meteorShard','Fragmento Estelar');if(end.event.type==='eclipse')this.unlock('eclipseGate','Portal do Eclipse');if(this.season.era>=5&&this.discoveries.eclipseGate)this.unlock('moonTemple','Templo da Lua');this.progress(end.event.reward,`Vitória no evento ${end.event.type}!`);this.audio?.play('victory')}else this.addFeed(`A ${end.event.type} passou; a ilha se recupera.`);this.save();this.notify()}if(Date.now()>=this.season.end)this.finishSeason()}
 unlock(key,name){if(!this.discoveries[key]){this.discoveries[key]=true;this.addFeed(`🔮 Descoberta desbloqueada: ${name}!`);this.audio?.play('discovery')}}
 finishSeason(){const leaders=this.rank('contribution').slice(0,3);this.season.winners=leaders;this.addFeed(`Temporada encerrada. Campeão: ${leaders[0]?.name||'Comunidade'}`);const old=this.season;this.reset();this.season.winners=old.winners;this.save();this.notify()}
 rank(field){return [...this.habitants].sort((a,b)=>(b[field]||0)-(a[field]||0)).slice(0,10)}
 integrity(){return Boolean(this.season&&this.season.era>=1&&this.season.era<=7&&this.habitants.every(x=>Number.isFinite(x.contribution)&&x.contribution>=0)&&this.dedup.ids.size<=this.config.maxEventIds)}
}
