import test from 'node:test';
import assert from 'node:assert/strict';
import {EventBus} from '../src/core/EventBus.js';
import {TikTokEventProvider} from '../src/events/TikTokEventProvider.js';
import {Game} from '../src/game/Game.js';

const packet=event=>JSON.stringify({kind:'event',event});
const event=(type,id,extra={})=>({id,type,userId:'tt-user',username:'TikToker',timestamp:Date.now(),...extra});
test('TikTok provider reports connection, disconnection and reconnection status',()=>{const bus=new EventBus(),p=new TikTokEventProvider(bus,{autoStart:false});p.receive(JSON.stringify({kind:'status',status:{status:'CONNECTED',username:'live'}}));assert.equal(p.getStatus().status,'CONNECTED');p.receive(JSON.stringify({kind:'status',status:{status:'DISCONNECTED'}}));assert.equal(p.getStatus().status,'DISCONNECTED');p.receive(JSON.stringify({kind:'status',status:{status:'RECONNECTING'}}));assert.equal(p.getStatus().status,'RECONNECTING')});
test('TikTok provider batches join, follow, likes, commands, gifts and streaks',()=>{const bus=new EventBus(),g=new Game(),p=new TikTokEventProvider(bus,{autoStart:false,batchSize:100});bus.on('external',e=>g.process(e));p.receive(packet(event('join','j')));p.receive(packet(event('follow','f')));p.receive(packet(event('like','l',{likeCount:100})));p.receive(packet(event('comment','c',{comment:'!construir'})));p.receive(packet(event('gift','g',{giftId:'1',giftName:'Rose',diamondCount:10,repeatCount:1,repeatEnd:true})));p.receive(packet(event('gift','streak-progress',{giftId:'2',diamondCount:50,repeatCount:3,repeatEnd:false})));p.receive(packet(event('gift','streak-end',{giftId:'2',diamondCount:50,repeatCount:3,repeatEnd:true})));p.flush();g.flushLikes(true);assert.equal(g.season.progress,12+1+10+30+330);assert.equal(g.habitants.length,1);assert.equal(p.getStatus().queue,0)});
test('TikTok provider ignores malformed packets and game rejects duplicate events',()=>{const bus=new EventBus(),g=new Game(),p=new TikTokEventProvider(bus,{autoStart:false});bus.on('external',e=>g.process(e));p.receive('{bad json');p.receive(packet(event('follow','same')));p.receive(packet(event('follow','same')));p.flush();assert.equal(p.getStatus().eventsIgnored,1);assert.equal(g.stats.processed,1);assert.equal(g.stats.ignored,1)});
test('TikTok provider handles 1,000 and 10,000 queued events without blocking integrity',()=>{const bus=new EventBus(),g=new Game(),p=new TikTokEventProvider(bus,{autoStart:false,batchSize:1000});bus.on('external',e=>g.process(e));for(let i=0;i<11000;i++)p.receive(packet(event('like',`like-${i}`,{likeCount:1})));while(p.flush());g.flushLikes(true);assert.equal(p.getStatus().eventsProcessed,11000);assert.equal(g.stats.failed,0);assert.ok(g.integrity())});
